[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Proxy API requests to backend (fixes cross-origin cookie issues)
# IMPORTANT: Replace the URL below with your actual Heroku backend URL
[[redirects]]
  from = "/api/*"
  to = "https://YOUR-HEROKU-APP.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

